[tool.ruff]
line-length = 80
target-version = "py312"

lint.select = ["ALL"]

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
docstring-code-format = true
skip-magic-trailing-comma = true
