# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# How to install:
# conda env create -f environments/environment_cuda11_8.yml

name: googlehydrology
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults  # Keep last
dependencies:
  - absl-py
  - bokeh
  - cachey
  - dask
  - gcsfs
  - h5py
  - hdf5
  - ipython
  - jupyter
  - matplotlib
  - memray
  - more-itertools
  - nbsphinx
  - nbsphinx-link
  - netcdf4
  - numba
  - numpy
  - pandas
  - parso
  - pydantic
  - pytest
  - pytest
  - pytest-cov
  - pytest-xdist
  - python=3.12
  - pytorch
  - pytorch-cuda=11.8
  - ruamel.yaml
  - ruff
  - scipy
  - sphinx
  - sphinx-rtd-theme
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm
  - xarray
  - zarr
